' Developer Express Code Central Example:
' How to perform drag-and-drop operation in a custom manner
' 
' This example illustrates how to perform the drag-and-drop operation in case of a
' ListBox drag-and-drop source. Since there is no built-in capability to
' accomplish this task, you should perform the drag-and-drop operation in a custom
' manner. To do this, use the following RichEditControl events: DragEnter,
' DragOver, DragDrop. Most part of the work is performed in the DragOver event
' handler. Here, you should update the RichEditControl.Document.CaretPosition
' property value according to the current mouse position (use the approach from
' the How to: Obtain the Document Position under the Mouse Cursor
' (ms-help://DevExpress.NETv10.2/DevExpress.WindowsForms/CustomDocument6012.htm))
' help section for this purpose). Also, you might want to draw a custom insertion
' marker in this event handler. Otherwise, you can use the standard caret. In
' latter case, just call the RichEditControl.Focus() method in the control's
' DragEnter event handler. Finally, note how the RichEditControl.ScrollToCaret
' Method
' (ms-help://DevExpress.NETv10.2/DevExpress.WindowsForms/DevExpressXtraRichEditRichEditControl_ScrollToCarettopic.htm)
' is used to scroll the document to the caret position if you move the caret
' outside of the visible document area.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=E2943

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
	Imports System
Namespace My


	''' <summary>
	'''   A strongly-typed resource class, for looking up localized strings, etc.
	''' </summary>
	' This class was auto-generated by the StronglyTypedResourceBuilder
	' class via a tool like ResGen or Visual Studio.
	' To add or remove a member, edit your .ResX file then rerun ResGen
	' with the /str option, or rebuild your VS project.
	<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()> _
	Friend Class Resources

		Private Shared resourceMan As Global.System.Resources.ResourceManager

		Private Shared resourceCulture As Global.System.Globalization.CultureInfo

		<Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")> _
		Friend Sub New()
		End Sub

		''' <summary>
		'''   Returns the cached ResourceManager instance used by this class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		''' <summary>
		'''   Overrides the current thread's CurrentUICulture property for all
		'''   resource lookups using this strongly typed resource class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set(ByVal value As System.Globalization.CultureInfo)
				resourceCulture = value
			End Set
		End Property
	End Class
End Namespace